ScoreCategory.create!(name: 'General', description: 'Not a specific category; used for general, non-specific scores', general: true)
ScoreCategory.create!(name: 'Funny', description: 'providing fun; causing amusement or laughter; amusing; comical')
ScoreCategory.create!(name: 'Important', description: 'of much or great significance or consequence')
ScoreCategory.create!(name: 'Easy', description: 'not hard or difficult')
ScoreCategory.create!(name: 'Unique', description: 'having no like or equal; unparalleled; incomparable')
ScoreCategory.create!(name: 'Intelligent', description: 'having or showing intelligence, clever, bright, brilliant')
ScoreCategory.create!(name: 'Cool', description: 'neat, awesome, swell')
ScoreCategory.create!(name: 'Bold', description: 'not hesitating or fearful of actual or possible danger or rebuff')
ScoreCategory.create!(name: 'Honest', description: 'honorable in principles, intentions, and actions')
ScoreCategory.create!(name: 'Kind', description: 'of a good or benevolent nature or disposition')
ScoreCategory.create!(name: 'Helpful', description: 'giving or rendering aid or assistance; of service')
ScoreCategory.create!(name: 'Beautiful', description: 'having beauty; possessing qualities that give great pleasure or satisfaction to see, hear, thing about')